apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-container
    image: mysql:5.6
    env: 
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: mysql-root-password
    volumeMounts:
    - name: my-persistent-storage
      mountPath: "/var/lib/mysql"
    ports:
    - containerPort: 3306
  volumes:
  - name: my-persistent-storage
    persistentVolumeClaim:
      claimName: mysql-pv-claim
