version: '2'
services:

    proxy:
      build:
        context: ./images/proxy
      container_name: proxy
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - elasticsearch

    ## APP
    nginx-app-1:
      build:
        context: ./images/custom-nginx
      container_name: nginx-app-1
      restart: always
      ports:
        - "3333:80"
      logging:
        driver: fluentd
        options:
          fluentd-tag: "unparse.nginx1.docker.{{.Name }}"
      depends_on:
       - fluentd-es
       - elasticsearch

    ## APP
    nginx-app-2:
      build:
        context: ./images/custom-nginx
      container_name: nginx-app-2
      restart: always
      ports:
        - "4444:80"
      logging:
        driver: fluentd
        options:
          fluentd-tag: "unparse.nginx2.docker.{{.Name }}"
      depends_on:
       - fluentd-es
       - elasticsearch

    ## FLUENTD
    fluentd-es:
      build:
        context: ./images/fluentd-es
      container_name: fluentd-es
      ports:
        - 24224:24224
      depends_on:
       - elasticsearch

     ## ELASTIC_SEARCH
    elasticsearch:
      build:
        context: ./images/es
      command: elasticsearch -Des.network.host=0.0.0.0
      ports:
        - "9200:9200"
        - "9300:9300"
