version: '2'
services:

    ## APP
    nginx-app:
      build:
        context: ./images/custom-nginx
      container_name: nginx-app
      restart: always
      ports:
        - "80:80"
      logging:
        driver: fluentd
        options:
          fluentd-tag: "nginx.docker.{{.Name }}"
      depends_on:
       - fluentd-es
       - elasticsearch

    ## FLUENTD
    fluentd-es:
      build:
        context: ./images/fluentd-es
      container_name: fluentd-es
      restart: always
      ports:
        - 24224:24224
      depends_on:
       - elasticsearch

     ## ELASTIC_SEARCH
    elasticsearch:
      build:
        context: ./images/es
      command: elasticsearch -Des.network.host=0.0.0.0
      ports:
        - "9100:9100"
        - "9200:9200"
        - "9300:9300"

    ## KIBANA
    kibana:
      build:
        context: ./images/kibana
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
