version: '2'
services:

    proxy:
      build:
        context: ./images/proxy
      container_name: proxy
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - elasticsearch

    ## APP
    nginx-app-1:
      build:
        context: ./images/custom-nginx
      container_name: nginx-app-1
      ports:
        - "3333:80"
      logging:
        driver: fluentd
        options:
          fluentd-tag: "unparse.nginx1.docker.{{.Name }}"
          fluentd-address: "0.0.0.0:24224"
      depends_on:
       - elasticsearch

    ## APP
    nginx-app-2:
      build:
        context: ./images/custom-nginx
      container_name: nginx-app-2
      ports:
        - "4444:80"
      logging:
        driver: fluentd
        options:
          fluentd-tag: "unparse.nginx2.docker.{{.Name }}"
          fluentd-address: "0.0.0.0:24224"
      depends_on:
       - elasticsearch

    ## FLUENTD
    # fluentd-es:
    #   build:
    #     context: ./images/fluentd-es
    #   container_name: fluentd-es
    #   ports:
    #     - 24224:24224
    #   depends_on:
    #    - elasticsearch

     ## ELASTIC_SEARCH
    elasticsearch:
      image: ypereirareis/elasticsearch-head
      container_name: elasticsearch
      # build:
      #   context: ./images/es
      command: elasticsearch -Des.network.host=0.0.0.0
      ports:
        - "9200:9200"
        - "9300:9300"
