version: '2'
services:

    ## APP
    nginx-app:
      build:
        context: ./images/custom-nginx
      container_name: nginx-app
      restart: always
      ports:
        - "80:80"
      logging:
        driver: fluentd
        options:
          fluentd-tag: "nginx.docker.{{.Name }}"
      depends_on:
       - fluentd
       - elasticsearch

    ## FLUENTD
    fluentd:
      build:
        context: ./images/fluent-es
        args:
          proxy: http://utilservnexus:5XgmKC!zNj91Ys8qobTaG-@fw-t-net.mipih.net:3128
      container_name: fluentd
      restart: always
      ports:
        - 24224:24224
      depends_on:
       - elasticsearch

    ## ELASTIC_SEARCH && KIBANA
    elasticsearch:
      image: nshou/elasticsearch-kibana:latest
      ports:
        - "9200:9200"
        - "8081:5601"

    # ## ELASTIC_SEARCH
    # elasticsearch:
    #   image: elasticsearch:latest
    #   command: elasticsearch -Des.network.host=0.0.0.0
    #   ports:
    #     - "9200:9200"
    #     - "9300:9300"
    #
    # ## KIBANA
    # kibana:
    #   build:
    #     context: ./images/kibana
    #     args:
    #       proxy: http://utilservnexus:5XgmKC!zNj91Ys8qobTaG-@fw-t-net.mipih.net:3128
    #   ports:
    #     - "8081:5601"
    #   depends_on:
    #    - elasticsearch
