name: flutter_moviesapp_demo_firebase_remote_config
description: Demo of moviesDB App using Firebase Remote Config

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  firebase_remote_config: ^3.0.9
  
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  fl_chart: ^0.36.1
  provider: 
  data_table_2: 2.0.3
  # Helps to implement equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.3
  dropdown_button2: ^1.9.2
  js: ^0.6.0

  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.13.3

  # Functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.1.0
  
  # Widgets that make it easy to integrate blocs and cubits into Flutter. Built to work with package:bloc.
  flutter_bloc: ^7.3.0
  firebase_analytics_web: ^0.5.1+12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Tools to write binaries that run builders.
  build_runner: 

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: 

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/flaticon/