import 'package:json_annotation/json_annotation.dart';

part 'models.g.dart'; // This file is generated by running 'flutter pub run build_runner build'

@JsonSerializable()
class InvoiceResponse {
  final List<Invoice> invoices;

  InvoiceResponse({
    required this.invoices,
  });

  factory InvoiceResponse.fromJson(Map<String, dynamic> json) =>
      _$InvoiceResponseFromJson(json);
  Map<String, dynamic> toJson() => _$InvoiceResponseToJson(this);
}

@JsonSerializable()
class Invoice {
  @JsonKey(name: 'gcs_uri')
  final String gcsUri;

  final InvoiceData data;

  Invoice({
    required this.gcsUri,
    required this.data,
  });

  factory Invoice.fromJson(Map<String, dynamic> json) =>
      _$InvoiceFromJson(json);
  Map<String, dynamic> toJson() => _$InvoiceToJson(this);
}

@JsonSerializable()
class InvoiceData {
  @JsonKey(name: 'invoice_date')
  final String invoiceDate;

  @JsonKey(name: 'invoice_id')
  final String invoiceId;

  @JsonKey(name: 'total_amount')
  final String totalAmount;

  @JsonKey(name: 'receiver_name')
  final String receiverName;

  @JsonKey(name: 'supplier_email')
  final String supplierEmail;

  @JsonKey(name: 'supplier_name')
  final String supplierName;

  @JsonKey(name: 'currency')
  final String currency;

  @JsonKey(name: 'invoice_type')
  final String invoiceType;

  @JsonKey(name: 'supplier_address')
  final String supplierAddress;

  @JsonKey(name: 'supplier_website')
  final String supplierWebsite;

  @JsonKey(name: 'receiver_email')
  final String receiverEmail;

  @JsonKey(name: 'remit_to_address')
  final String remitToAddress;

  @JsonKey(name: 'line_items')
  final List<LineItem> lineItems;

  InvoiceData({
    required this.invoiceDate,
    required this.invoiceId,
    required this.totalAmount,
    required this.receiverName,
    required this.supplierEmail,
    required this.supplierName,
    required this.currency,
    required this.invoiceType,
    required this.supplierAddress,
    required this.supplierWebsite,
    required this.receiverEmail,
    required this.remitToAddress,
    required this.lineItems,
  });

  factory InvoiceData.fromJson(Map<String, dynamic> json) =>
      _$InvoiceDataFromJson(json);
  Map<String, dynamic> toJson() => _$InvoiceDataToJson(this);
}

@JsonSerializable()
class LineItem {
  @JsonKey(name: 'description')
  final String description;

  @JsonKey(name: 'quantity')
  final String quantity;

  @JsonKey(name: 'unit_price')
  final String unitPrice;

  @JsonKey(name: 'amount')
  final String amount;

  LineItem({
    required this.description,
    required this.quantity,
    required this.unitPrice,
    required this.amount,
  });

  factory LineItem.fromJson(Map<String, dynamic> json) =>
      _$LineItemFromJson(json);
  Map<String, dynamic> toJson() => _$LineItemToJson(this);
}
