name: travel_explorer
description: "Another travel explorer application."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # Local package reference
  travel_rating:
    path: ./../packages/travel_rating

  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  google_maps_flutter: ^2.10.1
  location: ^8.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  firebase_core: ^3.12.1
  firebase_vertexai: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.3
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/