name: data_fetcher_service
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  functions_framework: ^0.4.1
  json_annotation: ^4.8.1
  shelf: ^1.0.0
  gcloud: ^0.8.8
  intl: ^0.18.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.4
  functions_framework_builder: ^0.4.7
  http: ^0.13.0
  json_serializable: ^6.7.0
  lints: ^2.0.0
