name: 'shelf_with_test'
version: 0.0.1
description: A web server built using the shelf package.
#author: bwnyasse <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.10.0 <0.14.0'
  shelf: '>=0.6.0 <0.7.0'
  shelf_rest:
  logging:
