version: '2'

services:

  env-dev:
    build:
      context: .
    image: bwnyasse/typesafe-activator-scala:1.3.12_2.12.0
    stdin_open: true
    tty: true
    ports:
     - 9000:9000
     - 9999:9999
     - 8888:8888
    command: bash
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/bwnyasse/work/project/learning-box/play/cache-ignore/root:/root/activator-cache
      - /home/bwnyasse/work/project/learning-box/scala:/code
