version: '2'

services:

  env-dev:
    build:
      context: .
    image: bwnyasse/typesafe-activator:1.3.6
    stdin_open: true
    tty: true
    ports:
     - 9000:9000
     - 9999:9999
     - 8888:8888
    command: bash
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      #- ./meo/code:/code
      # - ./asroot/:/root
