name: flutterauth0
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  go_router: ^2.0.0
  google_fonts: ^2.1.0
  json_annotation: ^4.0.1
  macos_ui: ^0.10.0+1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.1.0
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.9.0
  json_serializable: ^4.1.3
  flutter_lints: ^2.0.0
  flutter_appauth: ^4.2.1


flutter:
  uses-material-design: true
  assets:
    - assets/
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'
