
version: '2'
services:

  proxy:
      build: ./proxy
      container_name: registry_proxy_container
      restart: always
      ports:
        - "80:80"
      depends_on:
          - registry

  registry:
    image: registry:2
    container_name: registry_container
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /registry/data:/var/lib/registry


