
version: '2'
services:

  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /registry/data:/var/lib/registry

  proxy:
      image: nginx
      container_name: registry_proxy
      restart: always
      ports:
        - 80:80

