baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Boris-Wilfried'
theme = 'oloodi-hugo-clean'

[pagination]
  pagerSize = 4

[params.social]
linkedin = "https://linkedin.com/in/yourprofile"
github = "https://github.com/yourusername"
twitter = "https://twitter.com/yourhandle"
medium = "https://medium.com/yourprofile"
instagram = "https://instagram.com/yourprofile"
