apiVersion: v1
kind: Pod
metadata:
  name: fruit-service
spec:
  containers:
    - name: fruit-service-container
      image: linuxacademycontent/legacy-fruit-service:1
    - name: haproxy-ambassador-container
      image: haproxy:1.7
      ports:
        - containerPort: 80
      volumeMounts:
        - name: config-volume
          mountPath: /usr/local/etc/haproxy
  volumes:
    - name: config-volume
      configMap:
        name: fruit-service-ambassador-config
        
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: fruit-service-ambassador-config
data:
  haproxy.cfg: |-
    global
      daemon
      maxconn 256

    defaults
      mode http
      timeout connect 5000ms
      timeout client 50000ms
      timeout server 50000ms

    listen http-in
      bind *:80
      server server1 127.0.0.1:8775 maxconn 32

