steps:
  # Step to access the secret and write it to the desired location
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'gcloud secrets versions access latest --secret=service-account-json-key > /workspace/google-cloud/demos/flutter_invoice_document_ai/backend/assets/sa-key.json']
    secretEnv: ['SERVICE_ACCOUNT_JSON_KEY']

  # Step to build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/bwnyasse/learning-box/google-cloud/demos/flutter_invoice_document_ai/backend:$COMMIT_SHA', '.']
    dir: 'google-cloud/demos/flutter_invoice_document_ai/backend'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/bwnyasse/learning-box/google-cloud/demos/flutter_invoice_document_ai/backend:$COMMIT_SHA']
    dir: 'google-cloud/demos/flutter_invoice_document_ai/backend'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'flutter-invoice-document-ai-backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/github.com/bwnyasse/learning-box/google-cloud/demos/flutter_invoice_document_ai/backend:$COMMIT_SHA'
    - '--region'
    - 'northamerica-northeast1'

images:
  - 'gcr.io/$PROJECT_ID/github.com/bwnyasse/learning-box/google-cloud/demos/flutter_invoice_document_ai/backend:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/service-account-json-key/versions/latest
      env: 'SERVICE_ACCOUNT_JSON_KEY'

timeout: '1200s'
